# RAG pipline на минималках

1. Система принимает вопрос от пользователя
2. Запрос преобразуется в «эмбеддинг» (векторное представление текста)
3. Из векторной базы извлекается несколько документов, на основе близости векторов (по сути, схожести между запросом и документом) или какого либо другого гибридного алгоритма
4. В LLM отправляется вопрос состоящий из: заготовленного промта, извлеченных документов, и самого вопроса пользователя
5. LLM формирует ответ учитывая контекст (извлечённые документы) и пользователь получает ответ


#### На основе этого пайплайна соберём минимальный рабочий пример

## Грузим данные

Структура датасета:
```
/dataset
  questions.csv   # таблица с вопросами, 15 штук
  texts.csv       # таблица с названием документов, 30 штук
  /texts          # тексты документов, формат page_id.txt
    1.txt         
    10.txt
    ...
```

In [2]:
import pandas as pd

In [3]:
q = pd.read_csv("./dataset_base2/questions.csv")
q

                                             question  page_id
0    Посещение завершено, как закрыть случай лечения?        2
1                   Как оформить  направление на МСЭ?       81
2   Как создать направление на диагностическое исс...       80
3                                   Как создать МКСБ?       54
4   Как оформить направление на плановую госпитали...        2
5            Как перейти в «План иммунопрофилактики»?        8
6                    Кака создавать реестры в ВебМИС?      171
7   Какую роль нужно добавить пользователю, чтобы ...       30
8                             Как создать новый МКАБ?       31
9   Как проверить факт прикрепления пациента в сис...       28
10  Какие поля являются обязательными при заполнен...       26
11    Как распечатать согласия пациента в стационаре?       54
12  Как выдать заключение по медицинскому осмотру,...        1
13          Как создать свидетельство о смерти (МСС)?       76
14  Как оформить Электронное свидетельство о рожде...       75

In [4]:
docs = pd.read_csv("./dataset_base2/texts.csv")
docs

,title,url,page_id
0,WEB Поликлиника: Врач поликлиники,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,2
1,Медико-социальная экспертиза,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,81
2,Лабораторно-диагностические исследования,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,80
3,WEB Стационар: Приемный покой,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,54
4,WEB Поликлиника: Врач поликлиники,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,2
5,WEB Поликлиника: Иммунопрофилактика,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,8
6,Реестры,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,171
7,WEB Регистратура: Создание и ведение расписания,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,30
8,WEB Регистратура: Создание и редактирование МКАБ,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,31
9,WEB Регистратура: Работа с МКАБ в синей версии,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,28
10,WEB Регистратура: Лист ожидания,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,26
11,WEB Стационар: Приемный покой,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,54
12,WEB Диспансеризация,https://sd.hostco.ru/projects/amurmis/wiki/WEB...,1
13,Демография: Свидетельство о смерти,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,76
14,Демография: Свидетельство о рождении,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,75
15,WEB Поликлиника: Вызов врача на дом,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,3
16,WEB Поликлиника: Журнал направлений,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,5
17,WEB Поликлиника: Лист нетрудоспособности,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,10
18,WEB Поликлиника: Просмотр статистических данны...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,12
19,WEB Стационар: Гемотрансфузия: Работа с заявка...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,43
20,WEB Стационар: Пакет направлений на исследования,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,51
21,Администрирование МИС: Создание Врачебных коми...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,63
22,Администрирование МИС: Создание новых пользова...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,65
23,Администрирование МИС: Настройки для отправки ...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,69
24,Правильное оформление и отправка СЭМД: Beta (S...,https://sd.hostco.ru/projects/amurmis/wiki/Bet...,89
25,Правильное оформление и отправка СЭМД: СЭМД (1...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,116
26,Правильное оформление и отправка СЭМД: СЭМД (2...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,138
27,Правильное оформление и отправка СЭМД: СЭМД (7...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,150
28,Правильное оформление и отправка СЭМД: СЭМД (9...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,158
29,Правильное оформление и отправка СЭМД: СЭМД (S...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,164

In [5]:
raw_texts = []
for index, row in docs.iterrows():
    with open(f"./dataset_base2/texts/{row['page_id']}.txt", "r") as f:
        raw_texts.append(f.read())

docs["text"] = raw_texts
docs

,title,url,page_id,text
0,WEB Поликлиника: Врач поликлиники,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,2,WEB Поликлиника: Врач поликлиники\n\nh1. Врач ...
1,Медико-социальная экспертиза,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,81,Медико-социальная экспертиза\n\nh1. Медико-соц...
2,Лабораторно-диагностические исследования,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,80,Лабораторно-диагностические исследования\n\nh1...
3,WEB Стационар: Приемный покой,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,54,WEB Стационар: Приемный покой\n\nh1. Приемный ...
4,WEB Поликлиника: Врач поликлиники,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,2,WEB Поликлиника: Врач поликлиники\n\nh1. Врач ...
5,WEB Поликлиника: Иммунопрофилактика,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,8,WEB Поликлиника: Иммунопрофилактика\n\nh1. Имм...
6,Реестры,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,171,Реестры\n\nh1. Реестры ОМС\n\n\nh2. Описание\n...
7,WEB Регистратура: Создание и ведение расписания,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,30,WEB Регистратура: Создание и ведение расписани...
8,WEB Регистратура: Создание и редактирование МКАБ,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,31,WEB Регистратура: Создание и редактирование МК...
9,WEB Регистратура: Работа с МКАБ в синей версии,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,28,WEB Регистратура: Работа с МКАБ в синей версии...
10,WEB Регистратура: Лист ожидания,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,26,WEB Регистратура: Лист ожидания\n\nh1. Лист ож...
11,WEB Стационар: Приемный покой,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,54,WEB Стационар: Приемный покой\n\nh1. Приемный ...
12,WEB Диспансеризация,https://sd.hostco.ru/projects/amurmis/wiki/WEB...,1,WEB Диспансеризация\n\nh1. Диспансеризация в w...
13,Демография: Свидетельство о смерти,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,76,Демография: Свидетельство о смерти\n\nh1. Свид...
14,Демография: Свидетельство о рождении,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,75,Демография: Свидетельство о рождении\n\nh1. Св...
15,WEB Поликлиника: Вызов врача на дом,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,3,WEB Поликлиника: Вызов врача на дом\n\nh1. Выз...
16,WEB Поликлиника: Журнал направлений,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,5,WEB Поликлиника: Журнал направлений\n\nh1. Жур...
17,WEB Поликлиника: Лист нетрудоспособности,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,10,WEB Поликлиника: Лист нетрудоспособности\n\nh1...
18,WEB Поликлиника: Просмотр статистических данны...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,12,WEB Поликлиника: Просмотр статистических данны...
19,WEB Стационар: Гемотрансфузия: Работа с заявка...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,43,WEB Стационар: Гемотрансфузия: Работа с заявка...
20,WEB Стационар: Пакет направлений на исследования,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,51,WEB Стационар: Пакет направлений на исследован...
21,Администрирование МИС: Создание Врачебных коми...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,63,Администрирование МИС: Создание Врачебных коми...
22,Администрирование МИС: Создание новых пользова...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,65,Администрирование МИС: Создание новых пользова...
23,Администрирование МИС: Настройки для отправки ...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,69,Администрирование МИС: Настройки для отправки ...
24,Правильное оформление и отправка СЭМД: Beta (S...,https://sd.hostco.ru/projects/amurmis/wiki/Bet...,89,Правильное оформление и отправка СЭМД: Beta (S...
25,Правильное оформление и отправка СЭМД: СЭМД (1...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,116,Правильное оформление и отправка СЭМД: СЭМД (1...
26,Правильное оформление и отправка СЭМД: СЭМД (2...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,138,Правильное оформление и отправка СЭМД: СЭМД (2...
27,Правильное оформление и отправка СЭМД: СЭМД (7...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,150,Правильное оформление и отправка СЭМД: СЭМД (7...
28,Правильное оформление и отправка СЭМД: СЭМД (9...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,158,Правильное оформление и отправка СЭМД: СЭМД (9...
29,Правильное оформление и отправка СЭМД: СЭМД (S...,https://sd.hostco.ru/projects/amurmis/wiki/%D0...,164,Правильное оформление и отправка СЭМД: СЭМД (S...

In [6]:
print(docs["text"][0])

WEB Поликлиника: Врач поликлиники

h1. Врач поликлиники

h2. Вызов пациентов и их неявка

Для приёма пациентов врач поликлиники работает с расписанием
{{1148cc74-2ad3-4d16-8cd6-91cd0e6de378.jpg}}

В расписании выберете пациента, которого вызываете к себе
{{c58f4f2c-34bc-47cf-b6b2-654f09c63c70.jpg}}

Левой кнопкой мыши нажмите на пациента и выберете «Пригласить пациента»
{{099bd7d4-e97e-4c55-9ad5-249729e8fd9d.jpg}}

Откроется окно с началом приёма и отсчетом времени приёма пациента
{{1dfccd2e-e535-4a3f-a6d1-f0db3f10f269.jpg}}

В данном окне на панели есть 4 действующие кнопки:
h1.  Прекратить вызов {{7d2ed089-1fe9-4e6e-a0c6-c5aecb749dbc.jpg}}
* Начать {{f570a03a-fc04-4fdb-b1d4-230b64f1534c.jpg}}
* Неявка пациента {{1e334a24-8ab2-4676-ba9a-88ee365dd3dc.jpg}}
* Следующий пациент {{ea849c6f-600c-49f2-adee-ca46f4890b76.jpg}}

Также имеется информация о пациенте, которого вызвали на приём. Чтобы начать приём нажмите на «Начать» {{f570a03a-fc04-4fdb-b1d4-230b64f1534c.jpg}}. Отсчет времени начнется по новой, а пациент в расписании будет выделен розовым цветом
{{69cb7035-0cdc-4728-9bfd-66d59be01f65.jpg}}

Для завершения вызова по пациенту нажмите {{f21fbabe-a669-496d-a3d5-7be6f7b3dcf8.jpg}} и завершите приём. До завершения приема по одному пациенту, можно вызвать второго, для этого нажмите кнопку {{ea849c6f-600c-49f2-adee-ca46f4890b76.jpg}}. Отобразится второй пациент в вызове, при этом предыдущий вызов не завершиться, а второй пациент, которого вызвали будет выделен зелёным цветом.
{{e253d897-8f92-4dfb-a3b4-29139d234382.jpg}}

Если пациент не явился, то нажмите на {{1e334a24-8ab2-4676-ba9a-88ee365dd3dc.jpg}}. Программа выдаст предупреждение, что далее с записью работать будет невозможно
{{acae9460-95e9-477a-907a-8f565b53ca8e.jpg}}

Нажмите кнопку  "Да", чтобы аннулировать запись, либо кнопку "Нет", если пациент явился.
При подтверждении неявки пациента в расписании его цвет изменится на серый, а статус изменится на «Неявка пациента»
{{d473a2bc-61fe-4fdc-a062-26bf3a4d1db3.jpg}}

Неявка также отмечается без вызова пациента. Для этого выберете пациента, который не пришел на приём, нажмите левой кнопкой мыши на него и выберете пункт "Неявка пациента"
{{d39ba312-92a3-4321-8744-264716aa2f00.jpg}}

Программа выдаст уведомление. Подтвердите неявку пациента
{{acae9460-95e9-477a-907a-8f565b53ca8e.jpg}}

Статус пациента изменился на "Неявка пациента", а пациент в расписании стал выделятся серым цветом
{{d473a2bc-61fe-4fdc-a062-26bf3a4d1db3.jpg}}

Перейти в ТАП вызванного пациента можно двумя способами:
1. Левой кнопкой мыши нажмите на пациента в расписании и выберете «Случай лечения»
{{43e17911-53f4-44c4-b12a-3d072cc52a55.jpg}}

2. Нажмите на номер, расположенный рядом со временем приема на панели
{{06a31865-1b68-4397-954c-ee84eb14cefe.jpg}}

В новом окне откроется ТАП.

h2. Случай лечения

Заполнение ТАП в МИС осуществляется через
Шаг 1. Зайти под врачом, у врача должна быть присвоена роль «Случай лечения» (роли присваивает администратор)
Шаг 2. Нажмите на уже записанного пациента в расписание врача и выберите вкладку случай лечения.
{{f20dbd0c-9b84-41ec-84ab-3d28ba8a8bfa.png}}

Шаг 3. В новой вкладке открывается ТАП (Талон Амбулаторного Пациента)

{{41158fa0-97a2-4bed-8d06-024e084d5544.png}}

В левой части экрана есть навигационная панель, для быстрого доступа к интересующим разделам.

{{836aaf3f-3338-4d98-878a-99732b539321.png}}

Панель навигации, поля для заполнения:
1.Осмотр
2.Персональные данные
3.Сведения о случае лечения
4.Анамнез
5.Жалобы
6.Медицинские записи
7.Диагнозы
8.Экстренные извещения
9.Регистры
10. Клинические рекомендации
11.Порядок оказания мед.помощи
12.План лечения и услуги
13.Журнал направлений
14.Иммунопрофилактика
15.Журнал справок
16.Сведения о врачебной комиссии
17.Закрытие ТАП
18.Сведения о лечении COVID-19
19.Сведения о направлении
20.Связанные документы

h3. Осмотр

В разделе «Осмотр» заполняется Анамнез, для начала заполнение нажмите {{9311dca9-5122-4819-9390-d20f3be47002.png}}  в появившейся строке для редактирования или вода данных нажмите {{24faac53-77f4-40e3-8cb0-ec1ed6ecfec3.png}}.

{{e51f2ec9-6395-4d31-9376-6d67134e0ba2.png}}

Также есть возможность добавить патологические реакции. Нажмите на стрелочку и кнопку «Добавить»
{{4a644bba-540b-494d-b7e6-eafdae88fd15.jpg}}

Заполните реакцию и результат, врач заполнится автоматически, но выбирается также из выпадающего списка и нажмите «Сохранить»
{{9b61a476-f6a5-4f44-80c3-0419f98c951f.jpg}}

Реакция будет добавлена. Есть возможность удалить или редактировать реакцию
{{f2cc4297-1430-41ae-8f4e-0fadc2b584b1.jpg}}

Если у пациента есть вредные привычки, то внесите их, нажмите «Сохранить». Список подлежит редактированию
{{0ed49730-2e1a-4cfb-aba9-2ce68f5c3d98.jpg}}

h3. Показатели здоровья

В разделе "Показатели здоровья" отображаются ранее заполненные показатели здоровья. Заполняются "Показатель" и "Группа показателей", также их можно заполнить по случаю лечения. Заполнение происходит по аналогии с предыдущим разделом.

{{84856ae1-d09c-4ff8-8b4a-a7145822f287.png}}

Добавлена группа "Клинический минимум обследования", для заполнения необходимо выбрать группу и внести значения, данные отображаются по последнему сохраненному значению обследования пациента внесенных в вручную.
{{ed944c5b-a6bf-4a30-9d33-f38ef03ecf0e.png}}


h3. Жалобы

В разделе «Жалобы» есть возможность выбрать предложенные варианты жалоб, либо их можно прописать вручную.

{{85f426ac-4b3e-4942-96ff-0abba83ac427.png}}

h3. Медицинские записи

{{4522ed1b-3d4c-4c4e-995c-d6726289a1f8.png}}

Откроется форма, где можно выбрать шаблон мед. записи.

{{cd47d560-e2ca-413f-8db2-0eaba212f58c.png}}

h4. Заполнение  шаблона МЗ "Осмотр врача по стандарту"2.0

В шаблоне «Осмотр врача по стандарту 2.0»,  заполняются только те поля, которые Вам необходимы. В печатной форме незаполненные поля не отображаются.
Используя функцию «Словарь» можно сохранить слова, фразы и предложения для последующего выбора и отражения в поле документа. Для отображения данных словаря под полем, необходимо нажать на кнопку "Закрепить"
{{9166132d-0dbb-4edb-8ce7-6c0eb341989a.png}}

Для внесение основного диагноза, нажимаем на кнопку «Основной». В открытом окне заполняем «Код по МКБ-10». Выбираем из выпадающего списка «Характер заболевания» и «Диспансерный учёт», при наличии описаний заполняем поле «Описание», нажимаем «Сохранить».
Для добавления сопутствующего и др. диагнозов, необходимо нажать на кнопку "Добавить диагноз". Открывается окно для заполнения, с возможностью выбора из выпадающего списка «Тип диагноза».
{{3359c84f-4c60-442c-a4f1-0e55ce791339.png}}
Заполняем данные по оказанной услуге. Выбираем из выпадающего списка «Услугу» и «Диагноз», нажимаем «Сохранить».
{{b1447083-7c83-4e18-b7fd-7cbdec01d653.png}}

h4. Функция "Заполнение по истории"

Заполнить медицинскую запись можно с помощью данных ранее внесенных в прошлые медицинские записи.
Для этого  в шаблоне №200 МЗ "Осмотр врача по стандарту 2.0" в верхней части меню выбрать значок  {{2e17ad96-ffae-425d-97c8-707548d1d5ff.png}} нажав на который откроется окно для выбора предыдущей оформленной мед.  записи.

{{2de9bb25-2837-4f6e-86ea-6363d67e2adf.png}}

Переносить из предыдущей медицинской записи в рамках данного случая лечения, даже если эту запись в нем оставил другой специалист.
Для переноса данных из предыдущей мед. записи следует включить чекбокс, тогда каждый раз при создание новой медицинской записи, автоматически будут переноситься значения из предыдущей.

{{5e002539-b0ed-4e37-a1d1-df111b062543.png}}

Переносить из предыдущей медицинской записи предыдущего случая лечения. С условием, что пациенту выставлен один и тот же диагноз. Также не имеет значение какой врач оставил запись.
Чтобы перенос был осуществлен, прежде чем создать запись в новом случае, нужно сперва установить тот же диагноз, как в случаи из которого хотим осуществить перенос. Диагноз должен совпадать до точки.
Для переноса данных из предыдущего лечения следует включить чекбокс:

{{dd1b35af-dc0b-4c4a-879d-99526a026289.png}}

Для поиска медицинской записи необходимо включить чекбокс поликлиника либо стационар (где была оформлена прошлая мед. запись).
Выбрать временной промежуток и нажать кнопку поиска:

{{8bf14c5c-045b-458d-8eff-a9d90b5d7e32.png}}

Программа сформирует список подпадающих под заданный фильтр медицинских записей:

{{4da2d107-09f6-4796-aa76-0c5c60bda81c.png}}

После выбора медицинской записи появится поле с ранее заполненной информацией которая может быть перенесена в текущую медицинскую запись:

{{dfa4ed88-1b56-46b2-9888-04a5405af107.png}}

Сведения из документы заполненного ранее будут перенесены в текущую мед. запись:

{{8f0a98fe-32ac-4e2a-aa80-f69965763f7d.png}}

Для сохранения заполненного шаблона и применения в работе есть функция "Избранные шаблоны"  {{6eaf4e09-aee0-48c2-9f2b-8aef697d2ce5.png}}

h4. Функция "Избранные шаблоны"

Для сохранения заполненного шаблона и применения в работе есть функция "Избранные шаблоны".
Информацию заполненного шаблона можно переносить в новые шаблоны "Осмотр врача по стандарту"2.0 любому пациенту.

1. Заполнить медицинскую запись  "Осмотр врача по стандарту 2.0"
2. В верхней части меню выбрать значок   {{6eaf4e09-aee0-48c2-9f2b-8aef697d2ce5.png}} нажав на который откроется окно "Избранные шаблоны"

{{d68f04cc-2aa2-4527-8751-870dcd2dac7a.png}}

3. Ввести название для нового шаблона и нажать кнопку  {{368bb7dc-4fd6-4b50-a36c-0efa8ebdc42d.png}}
Шаблон создан и будет отображаться в списке при открытии любого нового шаблона МЗ:

{{ef4a375e-54b3-4cd5-9649-178657fdc04a.png}}

Для изменения названия шаблона следует  нажать кнопку  {{3d94e988-cdba-465b-ad73-b02333f5ed87.png}}

Для сохранения изменений следует нажать кнопку  {{5bf7b812-6eec-41f4-8348-5493cb213c2d.png}}

Для удаления  шаблона следует  нажать кнопку {{c3e73ca4-287b-4738-90f0-ed765cf44bc8.png}}

Для поиска шаблона следует ввести название либо включить чекбокс для вывода на экран всех созданных ранее шаблонов  {{b55c9a2f-d0cf-478b-8755-4d57333da24f.png}}

4. Для применения шаблона:
4.1 в не заполненной медицинской записи на панели меню нажать кнопку {{6eaf4e09-aee0-48c2-9f2b-8aef697d2ce5.png}}
4.2 найти созданный в п. 3 шаблон из списка и нажать кнопку  {{b8cfafdb-e66b-4167-b6ce-aacb9e0b77a9.png}}
Данные из шаблона будут перенесены в новую мед.запись.

h4. Функция "Направление на исследование"

Чтобы создать направление на исследование пациенту через шаблон №200 МЗ "Осмотр врача по стандарту 2.0" нужно в верхней части шаблона в меню выбрать значок {{e73fac08-16da-49ee-bdc3-06ec39af2c1c.png}}, нажав на который откроется окно направлений

Для назначения лекарственного препарата необходимо заполнить поля:

- Дата направления - по умолчанию текущая, с помощью календаря можно выбрать иную дату, но не менее текущей;
- Время -  по умолчанию время открытия окна направлений, можно изменить вручную;
- МО лаборатории - заполняется выбором значения из справочника;
- Цель исследования - заполняется выбором значения из справочника;
- Причина направления - заполняется выбором значения из справочника;
- Контингент - заполняется выбором значения из справочника;
- Тип оплаты - заполняется выбором значения из справочника;
- CITO - срочное направление - активируется при нажатии на чекбокс;
- Повторное направление - активируется при нажатии на чекбокс;
- Диагноз - автоматически отображается диагноз из Случая лечения, при необходимости можно выбрать иной из справочника;
- Комментарий - заполняется с помощью ранее сохраненных данный в Справочнике либо вручную;
- Описание причины - заполняется с помощью ранее сохраненных данный в Справочнике либо вручную.

{{a60872ba-2873-46ef-92bc-7ca8c8258cd1.png}}

Чтобы  выбирать  направления из перечня нужно нажать на чекбокс:

{{487ed35a-7f28-4a68-aa43-b74bd1019598.png}}

Далее нажать на кнопку {{bc337ce9-6f9a-48cb-b870-5b9d791686cf.png}}

Для печати созданных направлений нужно нажать на кнопку {{c51fca0c-175a-4923-94ba-04546ca3de0d.png}}

Печатная форма направления на исследование:
{{0e841291-f8bc-4c8b-9c5a-a73cd767adf4.png}}

Проверить сохранённое исследование и присвоенный номер исследования можно через журнал направлений:

{{e913f3e8-6066-49ff-9a8c-27adf876106d.png}}

Выбрав направление через "Журнал направлений" откроется окно с ранее заполненной информацией о направлении и возможностью Аннулирования направления:

{{29da7c94-de35-4562-a321-8457af8b6aa1.png}}

Для возврата в шаблон 2.0 на верхней панели следует нажать на {{2a5f0c8b-843a-41a4-a778-02eb433b54b4.png}}

h4. Функция "Получение результатов исследований"

Чтобы добавить результаты ранее проведённых исследований в медицинскую запись нужно в шаблоне №200 МЗ "Осмотр врача по стандарту 2.0" в верхней части меню выбрать значок {{dc5209cd-9746-4b46-a6c6-aeda7c254350.png}}, нажав на который откроется окно "Результаты исследований"

Выбрать вид проведённого ранее исследования, отметив его нажав на {{bf2d5016-4b15-4663-a5d9-6b759b3dd19f.png}}

{{b17749a4-ee8a-4706-9d4f-8496fa731b5c.png}}

Далее выбрать дату для поиска исследования и нажать на кнопку "Обновить"

{{24353495-6ac3-4861-af04-a59f7e176128.png}}

Выйдет список всех проведенных исследований подходящих под выставленные условия:

{{8dfeefbe-982e-4863-ab82-6029e3de4d7f.png}}

Далее следует нажать на подходящем исследовании  {{b10fcd16-c243-4413-9052-40f2660c47dc.png}}, откроется меню с перечнем дат и заключений о проведенном исследовании:

{{b372cd6d-b3ec-4168-bf1d-2d54acd0727c.png}}

Нажать на кнопку {{4ae8b23d-f59a-4c34-b4a9-5ca4d4da8dbd.png}}. После этого сведения о результатах исследования будут отражены в медицинской записи.

Для возврата в шаблон 2.0 на верхней панели следует нажать на {{2a5f0c8b-843a-41a4-a778-02eb433b54b4.png}}

В блоке инструментальная диагностика отражены добавленные нами данные.

{{25d29101-ed01-47eb-bb83-fb07f59209d1.png}}

h4. Функция "Запись на прием"

Для записи на прием не выходя из Случая лечения можно воспользоваться шаблоном №200 МЗ "Осмотр врача по стандарту 2.0"
В верхней части шаблона в меню выбрать значок часы, нажав на который откроется окно записи в расписание на прием

{{a682cf29-894b-4e41-9d19-0a756cc91bd7.png}}

{{13ac3522-db6b-4284-9102-877ace819c69.png}}

Далее выбираем создание записи на прием для текущего либо иного врача

{{765025d6-f5bc-4410-b396-ae5642c176c7.png}}

Запись на прием для текущего врача

Выбираем дату приема, включаем чекбокс "Предварительная запись" при необходимости

{{48bea1b1-5a83-48bc-8fd2-13edad022e6e.png}}

Если у врача нет приема на выбранную дату выйдет предупреждение:

{{3349576c-173e-4e83-8a1d-56bd28d337dd.png}}

При наличии расписания у врача выйдет список свободных временных ячеек в расписании. Выбираем время двойным нажатием мыши.

{{c02dcba3-4066-4b41-ae77-520df61388ed.png}}

Предусмотрена возможность записи вне расписания внизу списка {{cff01888-461f-48aa-8dd2-bef67d850ce0.png}}

В поле "Примечание" можно ввести комментарий (не обязательно для заполнения)
{{51732e0e-646c-4999-9954-fda2efd3a3c1.png}}

Нажимаем кнопку  {{6a389ba1-6274-435a-b706-fa417f324533.png}}

В блоке "Время записи на прием" ячейка с выбранным временем перекрасится из зелёной в красный цвет, отобразится информация с ФИО и датой рождения пациента.

{{aa889397-268d-4e48-8d9b-091aa4ff8f39.png}}

Запись пациента на прием произведена.
Автоматически информация о записи отразится в расписании врача.

{{777e4bc2-f3b1-4819-ac80-438201280005.png}}

Для возврата в шаблон 2.0 на верхней панели следует нажать на {{2a5f0c8b-843a-41a4-a778-02eb433b54b4.png}}

Запись на прием другому врачу/кабинет/оборудование/в другое МО

После выбора вида записи "Выбрать ресурс" выбираем из списка "Тип записи": к другому врачу, оборудование либо кабинет. Например делаем запись на прием в к другому специалисту.

{{bf0fd78c-7ebd-4641-af9c-7c88ac1b2ed2.png}}

Необязательные фильтры: "Специальность", "Тип записи", "Отделение" можно заполнить выбором значений из справочников:

{{85015b3e-f833-40ef-84ec-696c538d3ade.png}}

Обязательное поле "Ресурс", выбираем из справочника специалиста, у которого есть доступное расписание:

{{0912a9c2-d157-4709-a72f-e0513358517e.png}}

Выбираем дату приема, по умолчанию запись на прием будет предварительной

{{72bef014-ad4b-4d54-a65d-9c8a83055cb6.png}}

При наличии расписания у врача выйдет список свободных временных ячеек в расписании. Выбираем время двойным нажатием мыши.

{{6b4c6b12-5640-472f-877e-5575b5c1e89f.png}}

В поле "Примечание" можно ввести комментарий (не обязательно для заполнения)

{{45545cb1-5b29-4735-8963-eb14c25973a4.png}}

В блоке "Время записи на прием" ячейка с выбранным временем перекрасится из зелёной в красный цвет, отобразится информация с ФИО и датой рождения пациента.

{{11906e77-dc3f-452a-bc6c-d56080b0c618.png}}

Нажимаем кнопку  {{4a6c8c19-2220-4253-a8a6-5bfcaa3e24f0.png}}

Запись пациента на прием произведена.
Автоматически информация о записи отразится в расписании врача.

{{c9860e75-e36a-4280-987e-c4db4cd3bca0.png}}

Для возврата в шаблон 2.0 на верхней панели следует нажать на {{2a5f0c8b-843a-41a4-a778-02eb433b54b4.png}}

h3. Явка на ДУ

Для проставления следующей явки на прием в карту ДН, в верхней части шаблона в меню выбрать значок часы, нажимаем на кнопку "Явка на ДУ"
{{120f43b5-80e1-4d3a-8b39-48cc651f3241.png}}

В открывшейся форме указываем дату следующей явки в ручную или используя кнопки 1, 3, 6, 12 месяц (при выборе кол-во месяцев автоматически указывается дата явки расчет от текущей даты + выбранное кол-во месяцев) и нажимаем кнопку "Записать"
{{91fbc5dd-481c-42ec-834e-ab20ce318a8e.png}}


h4. Функция "Назначение ЛН"

Чтобы назначить ЛС пациенту через шаблон №200 МЗ "Осмотр врача по стандарту 2.0" нужно в верхней части шаблона в меню выбрать значок {{31d843a0-02ac-49b2-a974-26dc6c27815d.png}}, нажав на который откроется окно назначений

Для назначения лекарственного препарата необходимо заполнить поля:

- Дата назначения - по умолчанию текущая, с помощью календаря можно выбрать иную дату, но не менее текущей;
- Время -  по умолчанию время открытия окна назначений, можно изменить вручную;
- Диагноз - автоматически отображается диагноз из Случая лечения, при необходимости можно выбрать иной из справочника;
- Препарат - заполняется выбором значения из справочника;
- МНН - заполняется автоматически;
- Начало исполнения - по умолчанию дата текущая, с помощью календаря можно выбрать иную дату, но не менее текущей;
- Дни приёма - заполняются вручную;
- Интервал - заполняется выбором значения из справочника;
- Разовая доза - автоматически отображается доза выбранного выше препарата;
- Ед. измерения - автоматически отображается ед. измерения выбранного выше препарата;
- Раз в день - количество раз приемов препарата в день заполняются вручную, по умолчанию стоит 1;
- Кол-во на курс - количество раз приемов препарата на курс заполняются вручную, по умолчанию стоит 1;
- Способ приёма - заполняется выбором значения из справочника;
- Путь введения - заполняется выбором значения из справочника;
- Детализация дозировки - автоматически формируется по совокупности данных из полей: "Способ приёма". "Разовая доза", "Путь введения", "Раз в день", "Дней приема";
- Обоснование назначения - заполняется вручную.

{{255e1da6-3ada-435a-9017-c23159c20e23.png}}

После ввода данных, для добавления ЛС в предварительный лист назначений нажимаем на кнопку {{0ddff79d-23d2-4fff-a14e-03a6f300a873.png}}

{{f219f95d-7ab0-47bb-b6ca-716444f09d17.png}}

Для удаления ЛС из предварительного листа назначений следует нажать кнопку {{7f85135f-d9c7-4824-b95f-dfc0e642f1bc.png}}

Далее нажимаем кнопку  {{9d4b8237-08da-4f1d-a7ab-94efbbcc11af.png}}

Информация о назначенном ЛС будет перенесена в поле "Назначенные ЛС":

{{40ddeab1-bd2b-4eed-ade2-a1186bd9b691.png}}

Для печати рецептов следует нажать кнопку {{984f9856-44ff-4e03-ae67-1a5d47d801be.png}}

Перед этим при необходимости включить чекбокс "Латинское наименование"  {{f6b4abe5-9429-4e44-b181-b793e0257c69.png}}

и указать срок действия рецепта {{2bc477f2-5c59-4126-be27-5ec5fc795d1d.png}}

Печатная форма рецепта:

{{bdecb971-3098-42dc-96b4-6ce17ecaa198.png}}


## Создаём эмбеддинги

In [1]:
from sentence_transformers import SentenceTransformer

model = "ai-forever/ru-en-RoSBERTa"
embeddings = SentenceTransformer(model)

/home/egor/repo/Learning-nlp-models/.venv/lib64/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of RobertaModel were not initialized from the model checkpoint at ai-forever/ru-en-RoSBERTa and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of RobertaModel were not initialized from the model checkpoint at ai-forever/ru-en-RoSBERTa and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Это эмбеддинг модель от СБЕР, которая хорошо подходит для русского языка. Не топ 1 на текущий момент, но довольно известная и стабильная

Лидербор эмбеддинг моделей где можно посмотреть: [ссылка](https://huggingface.co/spaces/mteb/leaderboard)

### Как выглядит эмбеддинг?

In [7]:
some_text = "Пример текста для превращения в эммбеддинг"
some_embed = embeddings.encode(some_text)

In [10]:
some_embed[:5]

array([ 0.01027675,  0.00310721,  0.05322756, -0.0281062 , -0.04120595],
      dtype=float32)

In [11]:
# Размерность эмбеддинга
len(some_embed)

1024

## Векторная база
Воспользуемся самой простой базой, которая реализована "над" sqlite - `ChromaDB`  
Документация: [ссылка](https://docs.trychroma.com/docs)

Как работают векторные базы данных?

*Векторные базы данных хранят данные в виде многомерных числовых векторов, или эмбеддингов,
которые представляют семантическое значение различных типов данных, таких как текст, изображения или аудио.
Они используют специализированные структуры индексирования, такие как Hierarchical Navigable Small World (HNSW), для быстрого поиска по сходству,
находя векторы, математически близкие к заданному вектору запроса.
Это обеспечивает эффективный поиск данных с учётом контекста, основанный на значении, а не на точном соответствии ключевых слов,
что обеспечивает работу таких приложений, как семантический поиск, рекомендательные системы и контент-анализ на основе искусственного интеллекта.*

*@ ответ от неустановленного ИИ*

In [7]:
import chromadb
import os
import shutil

collection_name = "demo"

client = chromadb.PersistentClient("./data/chroma")
collection = client.get_or_create_collection(
    name=collection_name,
    metadata={"hnsw:space": "cosine"} # `cosine` - означает использовать "косинусную близость",
                                      # в качесте функции для определения степени близости
                                      # по сути, это просто косинус угла между двумя векторами
)

### Наполняем векторную базу данными

- Чем наполнять? Что мы хотим иметь? Что нужно знать?

Векторные базы, позволяют исполнять векторные операции на уровне своего движка, максимально оптимизируя это.  
Какие вектора у нас есть? Векторами буду являться эмбеддинги наших текстов.  

- А дальше?  

А дальше мы будем извлекать N документов которые близки по смысле с некоторым текстовым запросом, так же превращённым в эмбеддинг.  

Однако, стоит понимать что текст в эмбеддинге, не может быть превращён в обратно в текст. По этому, нам так же хотелсось бы сохранить и оригинальный текст, рядом с его эмебеддингом, ведь в итоге именно оригинальный текст пойдёт в LLM.  

- Как это сделать?  

Все бекторные базы позволяют, к каждому добавляемому ебмедингу, указать и любые нужны нам метаданные, в формате json (по сути векторные это nosql базы данны, с рядом доработок).  

`chromadb` так же позволяет указывать любые метаданные, однако, оригинальный текст, в ней должен быть сложен в специальное поле.  

- А вот ещё, как понять что хранить в метаданных?  

Зависит от задачи и что вы хотите получить на выходе (ну ещё бы, всё всегда зависит от вводных). Для данного примера нам достаточно будет хранить `page_id` для дальнешего расчёта метрик.

In [7]:
from chonkie import SemanticChunker, Visualizer

test_text = docs["text"][0]

chunker = SemanticChunker(
    embedding_model = model,
    chunk_size = 256
)

# chunks = chunker.chunk(test_text)

# for chunk in chunks:
#     print(f"Chunk: {chunk.text[:50]}...")
#     print(f"Tokens: {chunk.token_count}")

# viz = Visualizer()

# viz(chunks)

Some weights of RobertaModel were not initialized from the model checkpoint at ai-forever/ru-en-RoSBERTa and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
from chonkie import RecursiveChunker, Visualizer

chunker = RecursiveChunker(chunk_size=128).from_recipe("markdown", lang="en")

# test_text = docs["text"][0]

# chunks = chunker.chunk(test_text)

# for chunk in chunks:
#     print(f"Chunk: {chunk.text[:50]}...")
#     print(f"Tokens: {chunk.token_count}")

# viz = Visualizer()

# # viz(chunks)
# viz.save("chonkie.html", chunks)

In [10]:
for n, (index, row) in enumerate(docs.iterrows(), start=1):
    text = row["text"]                      # оригинальный текст
    # embed = embeddings.encode(text)  # текст в виде эмбеддинга
    meta = {"page_id": row["page_id"]}      # метаданные для этого "документа" внутри chromadb
    # id_ = f"id_{n}"                         # идентификатор "документа" (его требует chromadb)

    # вообще этот метод подразумевает добавление новых документов всей "пачкой" за один раз
    # это сделано ради оптимизации, потому что каждый новый документ, требует индексации
    # и расчёта его положения относительно всех других документов в коллецкции
    # а так же пересчёта положения остальных
    # но для простоты сделаем так
    # collection.add(
    #     ids=[id_],
    #     documents=[text],
    #     embeddings=[embed],
    #     metadatas=[meta]
    # )
    for n_chunk, chunk in enumerate(chunker.chunk(text)):
        collection.add(
            ids=[f"id_{n * 10000 + n_chunk}"],
            documents=[text],
            embeddings=[embeddings.encode(chunk.text)],
            metadatas=[meta]
        )

Попробуем что нибудь достать, используюя косинусово сходство

In [34]:
example_question = "Посещение завершено, как закрыть случай лечения?"

# Вопрос так же необходимо превратить в эмбедддинг
# Причём для документов в векторной базе и для поиска по ней, необходимо использовать одну и ту же эмбеддинг модель
# Иначе получится ерунда

query = embeddings.encode(q["question"][6])
results = collection.query(query)

In [17]:
type(results)

dict

In [11]:
results.keys()

dict_keys(['ids', 'embeddings', 'documents', 'uris', 'included', 'data', 'metadatas', 'distances'])

In [35]:
for key, value in results.items():
    if key == "documents":
        continue
    print(key, "|", value)

ids | [['id_230000', 'id_70004', 'id_70003', 'id_130000', 'id_220000', 'id_70006', 'id_180007', 'id_270001', 'id_20010', 'id_180000']]
embeddings | None
uris | None
included | ['metadatas', 'documents', 'distances']
data | None
metadatas | [[{'page_id': 65}, {'page_id': 171}, {'page_id': 171}, {'page_id': 1}, {'page_id': 63}, {'page_id': 171}, {'page_id': 10}, {'page_id': 138}, {'page_id': 81}, {'page_id': 10}]]
distances | [[0.3536921739578247, 0.3647890090942383, 0.3649359941482544, 0.3690760135650635, 0.38333940505981445, 0.410067081451416, 0.41516947746276855, 0.4165806770324707, 0.418285608291626, 0.4234558939933777]]

Что мы получили?
Мы имеем выборку из 5 ближайших к нашему вопросу документов, отсортированных по близости (от ближайшего до наиболее удалённого, в рамках выборки)

Поля `embeddings`, `uris`, `data`, нас пока что, не итересуют  
`included` - просто список не пустых полей  
`metadata` - все наши метаданные  
`distances` - значения метрики расстояния между запросом и каждым из документов в выборке

### А дальше?

Дальше, согласно пайплайну, идёт формирование контекста для отправки его в LLM. Однако, мы проускаем этот этап, потому что сейчас это не очень важно.

### Ну и что, всё? RAG готов? Расходимся, всем 100 баллов?

Нет. Просто так это не работает.  

Обратите внимание какой вопрос я использовал:  
*Посещение завершено, как закрыть случай лечения?*  
Это вопрос и датасета с вопросами. Его `page_id` - 2.  
То есть ответ на этот вопрос содержится в документе с `page_id == 2`.  

А мы что получили?
```
metadatas | [[{'page_id': 12}, {'page_id': 2}, {'page_id': 3}, {'page_id': 6}, {'page_id': 8}]]
```

Да, документ содержится в выборке, но идёт вторым. Мы не очень "попали" в нужный документ.  

В общем, здесь должно быть очевидно, что просто "из коробки" это не будет работать. Нужны определённая предобработка документов, прежде чем класть их в векторную базу. Этим мы и будем заниматься.

### Как понять насколько всё плохо?

Метрики! У RAG системы есть множество метрик, включая метрики для оценки качества ответа LLM.

У его компонента retriever (то что мы сейчас сделали это и есть retriever) тоже есть свои метрики. Давайте что нибудь посчитаем.
Мы воспользуемся метрикой MRR

MRR (Mean Reciprocal Rank) - средний обратный ранг, характеристика эффективности информационного поиска, зависящая от порядкового положения (ранга) первого релевантного результата. MRR оценивает «В среднем, как быстро в выборке появляется первый релевантный документ»  

Ранг для выборки, для одного запроса в бд:  
`Rank = 1 / p`  
где p - позиция, релевантного документа, в выборке  

Обратный ранг:  
`MRR = sum(Rank) / N`  
где N - количество осуществлённых запросов

#### Сделаем поиск по базе, по всем вопросам и определим позицию релавантного документа по `page_id`

In [11]:
def evaluate(model, questions, collection, total_docs):
  # model - embedding model
  # questions - evaluation questions
  # total_docs - for n_results return

  columns = ["question", "position", "score"]
  row_data = []

  for _, row in questions.iterrows():
    question = row["question"]
    y_true = row["page_id"]
    embedding = model.encode(question)

    results = collection.query(embedding, n_results=total_docs)

    for i, position in enumerate(results["metadatas"][0], start=1):
      
      if position["page_id"] == y_true:
        data_row = [question, i, 1/i]
        row_data.append(data_row)
        
        break
      
    else:
      data_row = [question, 0, 0]
      row_data.append(data_row)
    
  df = pd.DataFrame(row_data, columns=columns)
  df = pd.concat([df, pd.DataFrame(data={"question": "MRR", "position": df.score.sum()/df.shape[0], "score": "-------"}, index=[df.shape[0]])], axis=0)

  print(df)
  return df

In [13]:
res = evaluate(embeddings, q, collection, len(docs))
res

                                             question  position    score
0    Посещение завершено, как закрыть случай лечения?  1.000000      1.0
1                   Как оформить  направление на МСЭ?  1.000000      1.0
2   Как создать направление на диагностическое исс...  1.000000      1.0
3                                   Как создать МКСБ?  1.000000      1.0
4   Как оформить направление на плановую госпитали...  1.000000      1.0
5            Как перейти в «План иммунопрофилактики»?  1.000000      1.0
6                    Кака создавать реестры в ВебМИС?  2.000000      0.5
7   Какую роль нужно добавить пользователю, чтобы ...  1.000000      1.0
8                             Как создать новый МКАБ?  1.000000      1.0
9   Как проверить факт прикрепления пациента в сис...  1.000000      1.0
10  Какие поля являются обязательными при заполнен...  1.000000      1.0
11    Как распечатать согласия пациента в стационаре?  1.000000      1.0
12  Как выдать заключение по медицинскому осмотру,...  1.000000      1.0
13          Как создать свидетельство о смерти (МСС)?  1.000000      1.0
14  Как оформить Электронное свидетельство о рожде...  1.000000      1.0
15                                                MRR  0.966667  -------

                                             question  position    score
0    Посещение завершено, как закрыть случай лечения?  1.000000      1.0
1                   Как оформить  направление на МСЭ?  1.000000      1.0
2   Как создать направление на диагностическое исс...  1.000000      1.0
3                                   Как создать МКСБ?  1.000000      1.0
4   Как оформить направление на плановую госпитали...  1.000000      1.0
5            Как перейти в «План иммунопрофилактики»?  1.000000      1.0
6                    Кака создавать реестры в ВебМИС?  2.000000      0.5
7   Какую роль нужно добавить пользователю, чтобы ...  1.000000      1.0
8                             Как создать новый МКАБ?  1.000000      1.0
9   Как проверить факт прикрепления пациента в сис...  1.000000      1.0
10  Какие поля являются обязательными при заполнен...  1.000000      1.0
11    Как распечатать согласия пациента в стационаре?  1.000000      1.0
12  Как выдать заключение по медицинскому осмотру,...  1.000000      1.0
13          Как создать свидетельство о смерти (МСС)?  1.000000      1.0
14  Как оформить Электронное свидетельство о рожде...  1.000000      1.0
15                                                MRR  0.966667  -------

In [36]:
size = len(docs)

In [37]:
columns = ["question", "position", "score"]
df_data = []

for index, row in q.iterrows():
    question = row["question"]
    page_id = row["page_id"]
    query = embeddings.encode(question)

    # возьмём все документы, что есть в базе на данный момент
    # но это не очень показательно
    # в реальности мы ограничены размером контекстного окна LLM
    # мы просто не можем подать ей все документы
    results = collection.query(query, n_results=size)

    for n, (meta, score) in enumerate(
        zip(results["metadatas"][0], results["distances"][0]),
        start=1,
    ):
        retrieved_page_id = meta["page_id"]
        if page_id == retrieved_page_id:
            data_row = [question, n, score]
            df_data.append(data_row)
            break
    else:
        data_row = [question, 0, 0]
        df_data.append(data_row)

In [38]:
df = pd.DataFrame(df_data, columns=columns)
df

                                             question  position     score
0    Посещение завершено, как закрыть случай лечения?         1  0.323519
1                   Как оформить  направление на МСЭ?         1  0.237750
2   Как создать направление на диагностическое исс...         1  0.240156
3                                   Как создать МКСБ?         1  0.327383
4   Как оформить направление на плановую госпитали...         1  0.283147
5            Как перейти в «План иммунопрофилактики»?         1  0.275248
6                    Кака создавать реестры в ВебМИС?         2  0.364789
7   Какую роль нужно добавить пользователю, чтобы ...         1  0.317940
8                             Как создать новый МКАБ?         1  0.323538
9   Как проверить факт прикрепления пациента в сис...         1  0.351789
10  Какие поля являются обязательными при заполнен...         1  0.309919
11    Как распечатать согласия пациента в стационаре?         1  0.244536
12  Как выдать заключение по медицинскому осмотру,...         1  0.253849
13          Как создать свидетельство о смерти (МСС)?         1  0.203408
14  Как оформить Электронное свидетельство о рожде...         1  0.270274

---------------------------------------------
*Включение после написания всего ноутбука:*

```
Чисто визуально, вам может показаться, что мы имеем довольно много попаданий, эй кей position = 1  
Это так, но это только для этого, тестового датасета  
Я попробовал несколько вариантов датасетов, где:
- 15 вопросов и 30 документов всего (15 относятся, 15 "заполнитель")
- 15 вопросов и 45 документов всего (15 относятся, 30 "заполнитель")
- 15 вопросов и 60 документов всего (15 относятся, 45 "заполнитель")  

Ну и, что логично, чем больше размер всех документов, тем хуже он ищет, для таких "не очень" текстов

Остановился на 2м варианте, что бы имееть весьма близкие цифры MMR к
всему датасету и при этом что бы датасет не вышел слишком большим для погружения
```
---------------------------------------------

#### Посчитаем ранг для каждого запроса

In [39]:
df["rank"] = df["position"].apply(lambda x: 1 / x if x != 0 else 0)
df

,question,position,score,rank
0,"Посещение завершено, как закрыть случай лечения?",1,0.323519,1.0
1,Как оформить направление на МСЭ?,1,0.237750,1.0
2,Как создать направление на диагностическое исс...,1,0.240156,1.0
3,Как создать МКСБ?,1,0.327383,1.0
4,Как оформить направление на плановую госпитали...,1,0.283147,1.0
5,Как перейти в «План иммунопрофилактики»?,1,0.275248,1.0
6,Кака создавать реестры в ВебМИС?,2,0.364789,0.5
7,"Какую роль нужно добавить пользователю, чтобы ...",1,0.317940,1.0
8,Как создать новый МКАБ?,1,0.323538,1.0
9,Как проверить факт прикрепления пациента в сис...,1,0.351789,1.0
10,Какие поля являются обязательными при заполнен...,1,0.309919,1.0
11,Как распечатать согласия пациента в стационаре?,1,0.244536,1.0
12,"Как выдать заключение по медицинскому осмотру,...",1,0.253849,1.0
13,Как создать свидетельство о смерти (МСС)?,1,0.203408,1.0
14,Как оформить Электронное свидетельство о рожде...,1,0.270274,1.0

#### И наконец, общий обрабтный ранг для этих вопросов, для текущих документов в базе

In [41]:
MRR = df["rank"].sum() / size
print("{:.3f}".format(MRR))

0.483

Ну, в общем то, маловато. Что с этим делать? Вариантов много, но есть самый "напрашивающийся": нужно предобрабатывать документы. А именно разбивать их.  
Почему?  Ну потому разница между длиной текста в вопросе и длиной текста в документе, слишком велика. Надо как то дробить документы.
Вот этим мы и будем заниматься первое время: крутить вертеть тексты.

По этому, задача: используя приведённый код, попробовать каким либо образом (каким: на ваш выбор, какой придумаете, какой найдёте) разбить документы. НО! Вопросов 15, а всех документов 45 (специально, для больше приближённости к реальности). И разбивать нужно все документы, а не только те которые являются ответом на какой либо вопрос.

Для упрощения задачи, давайте будем считать, что любая разбитая часть документа имеет тот же `page_id` что и оригинальный документ.
Потому что в противном случае, пришлось бы сначала документы дробить, затем в дроблёных частях искать глазами где же ответ на этот вопрос, в каком куске из тех что получили когда разбили оригинальный документ.  
Сей неприятный труд, оставим на потом.
Удачи!

---------------------------------------------------------------------

In [18]:
с = ["question", "position", "score"]
df_second = []

for index, row in q.iterrows():
    question = row["question"]
    page_id = row["page_id"]
    query = embeddings.encode(question)
    results = collection.query(query, n_results=5)

    for n, (meta, score) in enumerate(
        zip(results["metadatas"][0], results["distances"][0]),
        start=1,
    ):
        retrieved_page_id = meta["page_id"]
        if page_id == retrieved_page_id:
            data_row = [question, n, score]
            df_second.append(data_row)
            break
    else:
        data_row = [question, 0, 0]
        df_second.append(data_row)

In [19]:
df2 = pd.DataFrame(df_second, columns=с)
df2["rank"] = df2["position"].apply(lambda x: 1 / x if x != 0 else 0)
df2

,question,position,score,rank
0,"Посещение завершено, как закрыть случай лечения?",1,0.323519,1.0
1,Как оформить направление на МСЭ?,1,0.237750,1.0
2,Как создать направление на диагностическое исс...,1,0.240156,1.0
3,Как создать МКСБ?,1,0.327383,1.0
4,Как оформить направление на плановую госпитали...,1,0.283147,1.0
5,Как перейти в «План иммунопрофилактики»?,1,0.275248,1.0
6,Кака создавать реестры в ВебМИС?,2,0.364789,0.5
7,"Какую роль нужно добавить пользователю, чтобы ...",1,0.317940,1.0
8,Как создать новый МКАБ?,1,0.323538,1.0
9,Как проверить факт прикрепления пациента в сис...,1,0.351789,1.0
10,Какие поля являются обязательными при заполнен...,1,0.309919,1.0
11,Как распечатать согласия пациента в стационаре?,1,0.244536,1.0
12,"Как выдать заключение по медицинскому осмотру,...",1,0.253849,1.0
13,Как создать свидетельство о смерти (МСС)?,1,0.203408,1.0
14,Как оформить Электронное свидетельство о рожде...,1,0.270274,1.0

In [20]:
MRR = df2["rank"].sum() / size
print("{:.3f}".format(MRR))

0.483

In [31]:
import re

def preprocess_headings(text):
    # Заменяем h1., h2., ... h6. на соответствующее количество #
    def repl(match):
        level = int(match.group(1))
        return '\n' + ('#' * level) + ' '
    return re.sub(r'\bh([1-6])\.\s*', repl, text)

test_text = preprocess_headings(test_text)